app:
  title: Frontdesk
  baseUrl: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud

backend:
  baseUrl: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud
  listen:
    port: 7000
  cors:
    origin: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      database:
        $env: PGDATABASE
      user:
        $env: PGUSER
      password:
        $env: PGPASSWORD
      host:
        $env: PGHOST
  csp:
    connect-src: ["'self'", 'http:', 'https:']

proxy:
  '/circleci/api':
    target: https://circleci.com/api/v1.1
    headers:
      Circle-Token:
        $env: CIRCLECI_AUTH_TOKEN

  '/jenkins/api':
    target: 'http://localhost:8080'
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER

  '/jira/api':
    target: https://tasks.trivago.com
    headers:
      Authorization:
        $env: JIRA_TOKEN
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian-Token: 'no-check'
      User-Agent: "MY-UA-STRING"

  '/bridge/api':
    target: https://trivago.bridgeapp.com/api
    headers:
      Authorization:
        $env: BRIDGE_TOKEN

jira:
  apiVersion: 2

bridge:
  url: https://trivago.bridgeapp.com

organization:
  name: trivago

gcpProjects:
  owner: trivago 
  repo: gcp-shared-config-stage

techdocs:
  storageUrl: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud/api/techdocs/static/docs
  requestUrl: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud/api/techdocs
  builder: 'local'
  generators:
    techdocs: 'local'
  publisher:
    type: 'googleGcs'
    googleGcs:
      bucketName: 'trv-frontdesk-techdocs-stage'
      credentials: 
        $file: '/etc/trv-shared-admin/key.json'

sentry:
  organization: trivago

rollbar:
  organization: trivago
  accountToken:
    $env: ROLLBAR_ACCOUNT_TOKEN

newrelic:
  api:
    baseUrl: 'https://api.newrelic.com/v2'
    key: NEW_RELIC_REST_API_KEY

auth:
  providers:
    google:
      development:
        appOrigin: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud
        secure: false
        clientId:
          $env: AUTH_GOOGLE_CLIENT_ID
        clientSecret:
          $env: AUTH_GOOGLE_CLIENT_SECRET
    github:
      development:
        appOrigin: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud
        secure: false
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET
        enterpriseInstanceUrl:
          $env: AUTH_GITHUB_ENTERPRISE_INSTANCE_URL

catalog:
  rules:
    - allow:
        - Component
        - API
        - Resource
        - Group
        - User
        - Template
        - System
        - Domain
        - Location
  locations:
    # Backstage Example Templates
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/springboot-grpc-template/template.yaml
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml
    - type: url
      target: https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml
    - type: url
      target: https://github.com/frontdesk-development/cookiecutter-argocd/blob/master/template.yaml
    - type: url
      target: https://github.com/trivago/cookiecutter-terraform/blob/master/template.yaml
    - type: url
      target: https://github.com/trivago/gcp-delivery-workshop/blob/master/template.yaml

integrations:
  github:
    - host: github.com
      apps:
        - $include: '/etc/github-admin/key.yaml'
  githubOrg:
    - host: https://github.com
      token:
        $env: GITHUB_TOKEN

lighthouse:
  baseUrl: http://frontdesk.sre-frontdesk.stage.europe-west4.tools.trv.cloud/lighthouse-be

grafana:
  baseUrl: http://monitoring.trivago.trv

scaffolder:
  github:
    token:
      $env: GITHUB_ACCESS_TOKEN
    visibility: internal # or 'public' or 'private'

kubernetes:
  serviceLocatorMethod: 'multiTenant'
  clusterLocatorMethods:
    - 'config'
  clusters:
    - url: https://10.245.248.194
      name: tools-prod0-eu-w4
      authProvider: 'serviceAccount'
      serviceAccountToken: 'token'
    - url: https://10.245.248.178
      name: tools-stage0-eu-w4
      authProvider: 'serviceAccount'
      serviceAccountToken: 'token'

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
  metrics:
  gcpConfig:
    projectId: 'trv-shared-billing'
    keyFilename: '/etc/trv-shared-admin/key.json'
    billingTable:
      $env: BILLING_TABLE

homepage:
  clocks:
    - label: UTC
      timezone: UTC
    - label: NYC
      timezone: 'America/New_York'
    - label: STO
      timezone: 'Europe/Stockholm'
    - label: TYO
      timezone: 'Asia/Tokyo'

pagerduty:
  eventsBaseUrl: 'https://events.pagerduty.com/v2'
